### ISSUE TITLE
Vorschlag eines Guides für jsonConfig

### ISSUE THREAD

**Issue by oweitman** [iobroker-community-adapters/responsive-design-initiative#7]
Hallo,

da die bisherige Schema.md etwas unhandlich ist, habe ich heute diese mal überarbeitet und versucht in eine
etwas didaktischere Struktur zu bringen.

hier der link zu meinem Fork des json-config repos, in dem sich die Beschreibungen befinden
https://github.com/oweitman/ioBroker.admin/blob/master/packages/jsonConfig/README.md

Wenn gewünscht, kann ich dann einen PR stellen

**Comment by Jey-Cee** [comment]
Gut das ich mich vorher dagegen Entschieden habe das heut in Angriff zu nehmen. 
Schon mal Danke. Ich schau mir das die Tage an.

**Comment by Apollon77** [comment]
@oweitman Bitte gern PR machen! Danke

**Comment by mcm1957** [comment]
PR wurde offensichtlich erstellt:
https://github.com/ioBroker/ioBroker.admin/pull/2781

**Comment by mcm1957** [comment]
Optische Aufarbeitung sieht für mich auch gut aus. Allerdings halte ich es für wenig sinnvoll dieselben Infos in einem README.md UND in SCHEMA.md abzulegen. Das garantiert dass mittelfristig die Info inkonsistent ist da eine Anpassung einmal nur in SCHEMA.md und einmal nur in README.md eingetragen wird. 

Da SCHEMA.md ja kein json Prüfschema ist sondern eine Textdatei die jetzt schon allgemeine Erläuterungen enthält erscheint es mir sinnvoll die Info im neuen Format dort abzulegen. Alternativ kann man SCHEMA.md auch auflassen bzw. durch eine Minidatei mit dem Hinweis wo die Infos nun leigen ersetzen da das Anpassen alelr Referenzen auf SCHEMA.md sicher einige Zeit dauern würde.

**Comment by oweitman** [comment]
guide ist publiziert.
ich schließe den issue

**Comment by mcm1957** [comment]
DANKE für deien Arbeit
